export const email = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((.[a-zA-Z0-9_-]{2,3}){1,2})$/
export const mobile = /^1[3|4|5|6|7|8|9][0-9]{9}$/
export const phone = /^(0\d{2,3}-\d{7,8})(-\d{1,4})?$/
export const url = /(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?/
export const idcard = /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/
export const pwd = /^[a-zA-Z]\w{5,17}$/
export const postal = /[1-9]\d{5}(?!\d)/
export const qqNum = /^[1-9][0-9]{4,10}$/
export const email = /^[\w-]+(\.[\w-]+)*@[\w-]+(\.[\w-]+)+$/
export const money = /^\d*(?:\.\d{0,2})?$/
export const ip = /((?:(?:25[0-5]|2[0-4]\\d|[01]?\\d?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d?\\d))/
